name: Native CI

on: push

jobs:

  verify:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - java11
        graalvm-version:
          - 21.1.0

    steps:
      - uses: actions/checkout@v1
      - name: Setup GraalVM CE
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: ${{ matrix.graalvm-version }}
          java-version: ${{ matrix.java-version }}
          native-image: "true"
      - name: Info
        run: mvn -version
      - name: Start Database
        run: ./docker/start_db_single.sh docker.io/arangodb/arangodb:3.7.12
      - name: verify
        run: mvn verify -Pnative

